#!/bin/bash
#  Read and echo each line. And, if it starts with "foobar:123:", print line 123
#  of foobar, using find(1) to find it.

while read input
do
    loc=$(echo "$input" | sed -n 's/^\([^ :]*\):\([0-9]*\):.*/\1 \2/p')
    len=${#loc}
    file=${loc% *}
    line=${loc#* }
    err=${input:$((len+2))}

    if [ $len -gt  0 ] 
    then
      echo "$file:$line: $(find . -name $file | xargs sed -n ${line}p)"
      echo -e "\t$err\n"
    fi
done

